### ISSUE TITLE
Loading phase screens from .fits

### ISSUE THREAD

**Issue by moniquecockram** [AOtools/soapy#132]
I am currently trying to load a phase screen from a fits file (one that was saved from a previous run of a simulation) into my simulation (a simple WFS, no DM). However, the WFS frames that are generated do not change over time.
This issue also occurs when getting the simulation to generate phase screens itself.

Something to note which might be helpful context: To do both of these things, my understanding is that the atmosphere parameter infinite must be set to False (and was done so when the above issues are occurring). However, when testing by setting infinite to True, the WFS frames do change over time.

Could you please provide any assistance in successfully loading a phase screen from a fits file?

Thank you for your help!

**Comment by ojdf** [comment]
Hi @moniquecockram!

Thanks for flagging this! I have just done a quick test using the sh_8x8.yaml config file and I have been unable to replicate it. I can save the screens using `sim.atmos.saveScrns()` then set the `scrnNames` parameter in the config file to a list of the file names of the screens, and they are loaded up on the next time and everything works, I get the same slopes output. You have to set both `infinite` and `randomScrns` to False otherwise the sim will just generate new screens. 

Could you post the config file you are using? At least the atmosphere part. Thanks!

**Comment by ojdf** [comment]
Hi @moniquecockram, glad it seems to be fixed! I will close this now but please get in touch if anything else does not work as expected
